M48
; DRILL file KiCad 10.0.3 date 2026-07-08T18:21:21
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-08T18:21:21+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.450
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X183.76Y-53.41
T2
X120.01Y-53.41
X175.25Y-69.41
T3
X151.65Y-43.65
X174.7Y-91.87
M30
